# activate conda env, then copy past the following command on terminal.
# python python tables_paper_ready2.py --input_dir inference/


import os
import pandas as pd
import numpy as np
import argparse
from pathlib import Path



def print_stratified_table(df, column_name, title, output_dir):
    """
    Stratifies the dataframe by a given column, calculates mean metrics,
    and prints/saves a formatted table with mathematically consistent PSNR.
    """
    print("\n" + "="*80)
    print(f"           STRATIFIED PERFORMANCE BY: {title.upper()}")
    print("="*80)

    # Bin into Low, Medium, High based on the raw difficulty metric
    df['stratum'] = pd.qcut(
        df[column_name].rank(method='first'),
        q=3,
        labels=['Low', 'Medium', 'High']
    )

    # Calculate means
    stratified_results = df.groupby(['stratum', 'Model'], observed=False)[['rmse', 'psnr', 'ssim', 'sam']].mean()

    # FIX: Recalculate PSNR from the mean RMSE for every group (Reviewer requested)
    for idx in stratified_results.index:
        avg_rmse = stratified_results.loc[idx, 'rmse']
        if avg_rmse > 0:
            stratified_results.loc[idx, 'psnr'] = 20 * np.log10(1.0 / avg_rmse)
        else:
            stratified_results.loc[idx, 'psnr'] = float('inf')

    # Desired order for the paper tables
    model_order = [
        'Prithvi (Full FT)',
        '3D U-Net',
        'Prithvi (Frozen)',
        'Mosaicking',
        'Zero-Shot Oracle',
        'Prithvi (Zero-Shot)'
    ]

    print(f"{'Stratum':<10} | {'Model':<22} | {'RMSE':<8} | {'PSNR':<8} | {'SSIM':<8} | {'SAM':<8}")
    print("-" * 80)

    # Store rows for saving to CSV
    csv_rows = []

    for stratum in ['Low', 'Medium', 'High']:
        for model_name in model_order:
            if (stratum, model_name) in stratified_results.index:
                row = stratified_results.loc[stratum, model_name]
                print(f"{stratum:<10} | {model_name:<22} | {row.rmse:<8.4f} | {row.psnr:<8.2f} | {row.ssim:<8.4f} | {row.sam:<8.4f}")
                
                row_dict = {'Stratum': stratum, 'Model': model_name}
                row_dict.update(row.to_dict())
                csv_rows.append(row_dict)
        print("-" * 80)
        
    # Save this specific table
    safe_title = title.lower().replace(' ', '_')
    pd.DataFrame(csv_rows).to_csv(os.path.join(output_dir, f"final_{safe_title}.csv"), index=False)


def compile_tables(args):
    print("Scanning inference folders for detailed patch metrics...")
    os.makedirs(args.output_dir, exist_ok=True)
    input_path = Path(args.input_dir)
    
    # Map the exact prefixes generated by inference to the paper display names
    model_file_prefixes = {
        'Prithvi (Full FT)': 'Prithvi_Full_FT',
        '3D U-Net': '3D_U-Net',
        'Prithvi (Frozen)': 'Prithvi_Frozen',
        'Prithvi (Zero-Shot)': 'Prithvi_Zero-Shot',
        'Mosaicking': 'Mosaicking',
        'Zero-Shot Oracle': 'Zero-Shot_Oracle' 
    }

    # --- 1. LOAD AND MERGE ALL RAW DATA ---
    all_dfs = []
    for display_name, prefix in model_file_prefixes.items():
        found_files = list(input_path.rglob(f"{prefix}_detailed_patch_metrics.csv"))
        if found_files:
            df = pd.read_csv(found_files[0])
            df['Model'] = display_name 
            all_dfs.append(df)
        else:
            print(f"Warning: Could not find detailed metrics for {display_name}")

    if not all_dfs:
        print("Error: No detailed patch metrics found. Check your input directory.")
        return

    merged_df = pd.concat(all_dfs, ignore_index=True)

    # --- 2. RUN STRATIFIED ANALYSES ---
    print_stratified_table(merged_df, 'difficulty_index', 'Overall Difficulty', args.output_dir)
    print_stratified_table(merged_df, 'heterogeneity', 'Spatial Heterogeneity', args.output_dir)
    print_stratified_table(merged_df, 'phenology_variability', 'Phenology Variability', args.output_dir)
    print_stratified_table(merged_df, 'cloud_persistence', 'Cloud Persistence', args.output_dir)

    # --- 3. RUN OVERALL PERFORMANCE ---
    print("\n" + "="*80)
    print("                       OVERALL PERFORMANCE (VERIFIED)")
    print("="*80)
    
    overall_results = merged_df.groupby('Model')[['rmse', 'psnr', 'ssim', 'sam']].mean()
    
    # APPLY THE PSNR FIX GLOBALLY
    for model in overall_results.index:
        avg_rmse = overall_results.loc[model, 'rmse']
        if avg_rmse > 0:
            overall_results.loc[model, 'psnr'] = 20 * np.log10(1.0 / avg_rmse)
            
    # Reorder based on paper presentation
    model_order = [
        'Prithvi (Full FT)', '3D U-Net', 'Prithvi (Frozen)', 
        'Mosaicking', 'Zero-Shot Oracle', 'Prithvi (Zero-Shot)'
    ]
    final_table = overall_results.reindex(index=[m for m in model_order if m in overall_results.index]).round(4)
    
    print(final_table)
    print("="*80)
    
    final_table.reset_index().to_csv(os.path.join(args.output_dir, "final_overall_performance2.csv"), index=False)
    print(f"\n All publication tables successfully generated and saved to: {args.output_dir}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input_dir', type=str, required=True, help='Directory containing the model subfolders')
    parser.add_argument('--output_dir', type=str, default='.', help='Directory to save final combined tables')
    args = parser.parse_args()
    compile_tables(args)
